### ISSUE TITLE
HTTP 410 for API calls with country code PL

### ISSUE THREAD

**Issue by Gnoupi** [Sholofly/ziggonext-python#34]
Hello,

I've tried to connect through Home Assistant with PL country code, and I'm gettinmg the following:
```
2021-04-18 15:10:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component ziggonext
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/homeassistant/setup.py", line 241, in _async_setup_component
    result = await task
  File "/data/data/com.termux/files/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/ziggonext/__init__.py", line 30, in setup
    api.connect()
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/ziggonext/ziggonext.py", line 268, in connect
    self.get_session_and_token()
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/ziggonext/ziggonext.py", line 58, in get_session_and_token
    self._get_token()
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/ziggonext/ziggonext.py", line 261, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/data/data/com.termux/files/home/hass/lib/python3.9/site-packages/ziggonext/ziggonext.py", line 257, in _do_api_call
    raise ZiggoNextConnectionError("API call failed: " + str(response.status_code))
ziggonext.exceptions.ZiggoNextConnectionError: API call failed: 410
```

So it looks like the API url is not correct anymore?
Is there any way I can help finding out the correct one (assuming it exists)?

**Comment by Sholofly** [comment]
Hi @Gnoupi , good to have you here. Unfortunately I don't have time today but I am eager to get it fixed for you. Can I contact you this week to get it to work? Do you have discord?

**Comment by Gnoupi** [comment]
Sure, gladly.
Gnoupi#1545

**Comment by Sholofly** [comment]
I have sent you a friendsrequest.

**Comment by Gnoupi** [comment]
Well, thanks for your help.
Looks like even if I access the same horizon tv site, I do not actually have the proper box for this, which is why there was an error.
It will work only for people who have the remote control accessible from the horizon tv site.

It's unclear which box will work in Poland. For sure not the previous Horizon box (https://www.google.com/search?hl=en&q=DMC7002KLG). The next one is not the same as the other countries: https://www.libertyglobal.com/the-mini-tv-box-our-smallest-greenest-set-top-box/. It might still have remote control, though. Something to check with another user (or me eventually if I do migrate to this)
